1. https://mp.weixin.qq.com/s/eBJWejt_ZoFuZ6hoGE3egA



2. https://mp.weixin.qq.com/s/GLc_-fmbi4cmE7KZbhuV_g  // 文章中解法三说的不清楚，可以看
   https://blog.csdn.net/DERRANTCM/article/details/46811855


3. https://mp.weixin.qq.com/s/oEjwj-WrL8m7eCBJRDBN-g  // 想到了递归，但是没想到用max去比较 
    // 还可以使用按层遍历二叉树

4. https://mp.weixin.qq.com/s/xlBN77iUhXZ1iCNh3xAcow 二叉树搜索第 K 大节点   中序遍历

 // 仔细想想 文章中java code的解法


5. https://mp.weixin.qq.com/s/EiECZ7T1uui69LS4SUUI0Q // 这个题目没思路，其实树的题目基本就是前，中，后三种遍历为基本。

//https://leetcode-cn.com/problems/er-cha-shu-zhong-he-wei-mou-yi-zhi-de-lu-jing-lcof/solution/mian-shi-ti-34-er-cha-shu-zhong-he-wei-mou-yi-zh-5/
// https://blog.csdn.net/ouyangyanlan/article/details/71516641